  server:
    port=8080

  spring:
    redis:
    database: 0
    host: 192.168.112.128
    password:
  timeout: 3600
  port: 6379
  pool:
  max-wait: 10000
  min-idle: 0
  max-idle: 8
  max-active: 8